---
total: 1000000
format: json
qps: 2

connectors:
  ad_click:
    connector:
      kafka:
        broker: redpanda:9092
        topic: ad_click
        timeout_ms: 10000
  ad_impression:
    kafka:
      broker: redpanda:9092
      topic: ad_impression
      timeout_ms: 10000
