---
total: 1000000
format: json
qps: 10

connector:
  kafka:
    broker: 127.0.0.1:29092
    topic: ad_impression
    timeout_ms: 10000

schema:
  client_id:
    type: long
    range: [1, 1000]
  user_id:
    type: long
    range: [1, 1000]
  ad_id:
    type: long
    range: [1, 10]
  user_name:
    type: name
  click_timestamp:
    type: timestamp
    timestamp:
      random_delay: 1s
