---
total: 1000000
format: json
qps: 10

connector:
  kafka:
    broker: 127.0.0.1:29092
    topic: ad_click
    timeout_ms: 10000

schema:
  client_id:
    long:
      start: 1
      stop: 1000
  user_id:
    long:
      start: 1
      stop: 1000
  ad_id:
    long:
      start: 1
      stop: 10
  user_name: name
  click_timestamp:
    timestamp:
      random_delay: 1s
