---
total: 10
format: json

connector:
  kafka:
    broker: 127.0.0.1:29092
    topic: test_topic
    timeout_ms: 1000

schema:
  platform:
    type: enum
    enum:
      - ios
      - android
  search_hash_id:
    type: string
  log_type:
    type: string
  view_action:
    type: string
  parent_token:
    type: string
  parent_id:
    type: string
  server_timestamp:
    type: timestamp
  query:
    type: stringzh
  tab_type:
    type: string
  content_type:
    type: string
  content_id:
    type: string
  publish_timestamp:
    type: timestamp
  container_index:
    type: int
  client_id:
    type: string
  member_id:
    type: long
  client_timestamp:
    type: timestamp
  page_elapsed:
    type: long
  container_type:
    type: string
  page_level1_id:
    type: string
  content_token:
    type: string
  element_type:
    type: string
  event_type:
    type: string
  block_text:
    type: string
  element_text:
    type: string
  view_url:
    type: string
  page_name:
    type: string
  search_source:
    type: string
