name: Docker Build for Workload Generator

on:
  # For manually triggering workflow
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "workload-generator/**"

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Build workload-generator
        run: |
          cd workload-generator
          cargo build --release

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./workload-generator
          push: true
          tags: |
            ghcr.io/singularity-data/workload-generator
